# Multi-Modal Safety Configuration
# This file contains all configuration parameters for the multi-modal safety system

multimodal_safety_node:
  ros__parameters:
    # Sensor Fusion Configuration
    fusion_method: "weighted_average"  # Options: weighted_average, kalman_filter, bayesian_fusion
    safety_update_rate: 10.0  # Hz
    sensor_timeout: 2.0  # seconds
    
    # Sensor Enable/Disable
    enable_vision: true
    enable_audio: true
    enable_tactile: true
    enable_proprioceptive: true
    enable_lidar: true
    
    # Sensor Weights for Fusion (must sum to 1.0)
    vision_weight: 0.3
    audio_weight: 0.2
    tactile_weight: 0.25
    proprioceptive_weight: 0.15
    lidar_weight: 0.1
    
    # Safety Thresholds
    collision_threshold: 0.7
    human_proximity_threshold: 0.8
    velocity_threshold: 0.6
    workspace_boundary_threshold: 0.5
    emergency_stop_threshold: 0.9
    
    # Vision Sensor Configuration
    vision:
      camera_topic: "/camera/color/image_raw"
      depth_topic: "/camera/depth/image_raw"
      processing_rate: 30.0  # Hz
      confidence_threshold: 0.5
      object_detection_enabled: true
      human_detection_enabled: true
      obstacle_detection_enabled: true
    
    # Audio Sensor Configuration
    audio:
      audio_topic: "/audio/features"
      processing_rate: 44.1  # Hz
      confidence_threshold: 0.6
      voice_detection_enabled: true
      emergency_sound_detection_enabled: true
      noise_filtering_enabled: true
    
    # Tactile Sensor Configuration
    tactile:
      tactile_topic: "/tactile/features"
      processing_rate: 100.0  # Hz
      confidence_threshold: 0.7
      contact_detection_enabled: true
      pressure_monitoring_enabled: true
      force_limiting_enabled: true
    
    # Proprioceptive Sensor Configuration
    proprioceptive:
      imu_topic: "/imu/data"
      joint_states_topic: "/robot/joint_states"
      processing_rate: 100.0  # Hz
      confidence_threshold: 0.8
      joint_limit_monitoring_enabled: true
      velocity_monitoring_enabled: true
      acceleration_monitoring_enabled: true
    
    # LIDAR Sensor Configuration
    lidar:
      scan_topic: "/lidar/scan"
      pointcloud_topic: "/lidar/points"
      processing_rate: 10.0  # Hz
      confidence_threshold: 0.9
      obstacle_detection_enabled: true
      distance_monitoring_enabled: true
      mapping_enabled: true
    
    # Cross-Modal Correlation Matrix
    correlation_matrix:
      vision_lidar: 0.8
      vision_audio: 0.3
      vision_tactile: 0.2
      vision_proprioceptive: 0.1
      lidar_audio: 0.2
      lidar_tactile: 0.3
      lidar_proprioceptive: 0.2
      audio_tactile: 0.6
      audio_proprioceptive: 0.1
      tactile_proprioceptive: 0.4
    
    # Performance Configuration
    performance:
      max_processing_time: 0.1  # seconds
      buffer_size: 100
      enable_performance_monitoring: true
      enable_metrics_publishing: true
    
    # Safety Event Configuration
    safety_events:
      enable_event_logging: true
      event_history_size: 1000
      critical_event_timeout: 5.0  # seconds
      event_severity_levels:
        low: 0.3
        medium: 0.6
        high: 0.8
        critical: 0.9
    
    # Integration Configuration
    integration:
      enable_safety_arbiter_integration: true
      enable_llm_integration: true
      enable_simulator_integration: true
      enable_orchestrator_integration: true 